### ISSUE TITLE
Recommendation 11: Registry VS cross repository queries. 

### ISSUE THREAD

**Issue by bcorrie** [airr-community/common-repo-wg#12]
My feeling is that having a registry and the capability to perform cross repository queries are two independent issues and should not be listed together. I would recommend striking the second phrase of this recommendation and adding some wording around the FAIR principles instead. Something like:

Recommendation 11: The AIRR Community should maintain a central registry of compliant repositories, providing a mechanism for AIRR Repositories to be "Findable" (see FAIR principles https://www.nature.com/articles/sdata201618).

It seems like a mistake to mix the registry capability that Recommendation 10 and Recommendation 11 define with the ability to perform operations/queries across repositories (the second phrase in Recommendation 11). The registry should be primarily about facilitating the Findable components of the FAIR aspects of AIRR repositories.

- Note:  This does not mean that a cross-repository operation/query capability should not exist. This is what iReceptor does. I think it is a mistake to have that capability explicitly linked to the registry. 
- Note: Recommendation 7 states that their should be a standard set of queries that each repository should support. This, combined with Recommendation 11 that repositories are FAIR means that it is possible to implement a tool or gateway that support cross-repository queries. It just shouldn't be the registry that does it!

**Comment by bcorrie** [comment]
Should we close this issue given the movement on the decisions. I think this is resolved in terms of the decision to use the DataMed registry - https://datamed.org/index.php

If no one comments otherwise I will close the issue shortly...

Brian

**Comment by schristley** [comment]
I've spent a little time looking at DataMed and their [API](https://datamed.org/APIDoc.php) doesn't seem to indicate how to search for repositories. It only indicates searching for datasets. On the home page however, it does let you search for repositories from the web form, so I'm not sure if the API is under-documented or it's designed that way.

We might need to start a conversation with the DataMed people to see if they will meet our requirements.

**Comment by bcorrie** [comment]
Have you looked at FairSharing.org? They have an API, but I think you need an API key before you can look at the API documentation in detail (which is odd).... They used to be biosharing.org...

https://fairsharing.org/license
https://fairsharing.org/api#/

I haven't looked at the details of the API, has anyone else. I know that we have registered iReceptor on this site.

https://fairsharing.org/biodbcore-000974

Brian

**Comment by bcorrie** [comment]
MiAIRR is also listed there as a standard... 

https://fairsharing.org/bsg-s000689

**Comment by bcorrie** [comment]
@schristley should we close this issue and create a separate one around registry implementation... It is a bit confusing having the discussion around the registry API in this issue...

**Comment by schristley** [comment]
@bcorrie sure

**Comment by bcorrie** [comment]
Closing, ongoing registry discussion in Issue #18
