### ISSUE TITLE
Recommendations 12 & 13: Whereabouts of processed sequences

### ISSUE THREAD

**Issue by bussec** [airr-community/common-repo-wg#15]
Currently (c8e751a5490ae3e7ed8147cdf7c95279c75d7e50) recommendations 12 and 13 suggest that:
1. raw data is deposited in SRA/ENA
2. processed data and annotations are deposited in a `compliant AIRR repository`

However, according to current MSWG recommendations processed data and *some* annotations should in addition be deposited in GenBank/ENA/DDBJ.

The wording of the recommendations should be changed accordingly.

**Comment by lgcowell** [comment]
Hi Christian,

I revised the wording of Recommendations 13 and 14 to address this concern. Please review and let me know.

Thank you,

Lindsay

**Comment by bussec** [comment]
Ok, thanks!
