### ISSUE TITLE
AIRR Data Commons - is this a term we can/should use?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/common-repo-wg#19]
Hello All, 

Today, on the iReceptor web site, in our papers, and in our grant proposals, we talk about the iReceptor Data Commons. This is a network of distributed data repositories which currently consists of the existing iReceptor repositories and VDJserver's public repository. 

Quite often we also use the term AIRR Data Commons to refer to what we anticipate will become the international network of data repositories that follow the MiAIRR standard and more importantly adhere to the CRWG's Recommendations, implement the CRWG API, and are discoverable in the AIRR Registry. Tools like the iReceptor Scientific Gateway (as well as any other tool) then query the "AIRR Data Commons" to find, explore, and analyze data. Once the above are implemented, there would no longer be two Data Commons, there would only be one - the AIRR Data Commons...

My question to the group is - is this terminology something that we want to encourage? Do people like (or dislike) the AIRR Data Commons concept/terminology?

Brian

**Comment by lgcowell** [comment]
I like it.

**Comment by bcorrie** [comment]
Made changes to the Recommendations file to use the AIRR Data Commons terminology in commit here:

https://github.com/airr-community/common-repo-wg/blob/issue-19/recommendations.md

Please have a look and comment... We can discuss at next meeting.

**Comment by schristley** [comment]
Do we need to update the version and date on the document?

**Comment by bcorrie** [comment]
Hmm, good point. I will do that, but this also points out that the current version says it is:

v0.4.0 (draft)

I think we should be saying the current version is

v0.4.0 (approved by the AIRR Community, AIRR Community Meeting, December 2017)

**Comment by lgcowell** [comment]
I agree we should update that to reflect approval.  Thanks!

**Comment by bcorrie** [comment]
I made the change to v0.4.0 on the master branch. I also fixed the URL so that it points to the AIRR meeting page on the TABS site.

**Comment by schristley** [comment]
Sorry to make more work @bcorrie, but maybe the readme for the repository can give a list? Right now it just gives a link to the recommendations document. Or another idea is to put a simple changelog in the recommendations document itself, this is common technique too.

v0.4.1 - Added verbiage for AIRR Data Commons, blah blah
v0.4.0 - Approved by the AIRR Community, AIRR Community Meeting, December 2017

There probably should be at least a "permanent" link to the original approved document, without having to search through the github commit history.

**Comment by bcorrie** [comment]
@schristley made the changes requested above, permanent link to the original recommendations commit, and I tagged the v0.5.0 version with the AIRR Data Commons link.

Safe to close this issue?

**Comment by schristley** [comment]
looks good!
