### ISSUE TITLE
Create a list of AIRR-seq data repositories 

### ISSUE THREAD

**Issue by bcorrie** [airr-community/common-repo-wg#20]
We want to have a list of repositories that store AIRR-seq (or AIRR-seq related data) as a general list of repositories that are useful to the community. Note that this is NOT a list of AIRR Data Commons compliant repositories, it is a list of repositories that might be of interest to the broad community.

**Comment by bcorrie** [comment]
Current suggestion from the executive is that this list live on the b-t.cr site as it is a more broad scope than the AIRR site and it already has some general lists on the site ,for example:

https://b-t.cr/t/publicly-available-airr-seq-data-sets-b-cells-continued/525

**Comment by bcorrie** [comment]
Hello All,

An update on this issue. I have created a page that lists repository that store public data on b-t.cr here:

https://b-t.cr/t/publicly-available-airr-seq-data-repositories/610

I started with listing two, the iReceptor IPA and the VDJServer repository, which are the ones I know the most about 8-).

I made up a format for the list that is somewhat arbitrary, but contained information that I thought might be useful. In particular, I chose to go the route of listing the repositories themselves (the entitites that have query APIs), not the web portals that are used to query them. I added 

I also started using the AIRR CRWG Repertoire and Rearrangement terminology in describing the API entry points for repositories if they have them. Of course both IPA and VDJServer have such APIs - using the iReceptor naming convention.

@schristley feel free to have a look and edit as you see fit. I wasn't sure how to handle VDJServer, as it in essence has two different repositories, the public facing one that iReceptor can search and the private VDJServer repository where users store their working data and run their pipelines. It might make sense to have two repositories for VDJServer in this case?

If anyone has any comments feel free to add them here, we can discuss at the next meeting. Hopefully by the next meeting I will be able to add some non iReceptor API repositories. If anyone wants to add any repositories, please feel free to either add them directly to the b-t.cr site or send me info and I will add them as I get time.

Brian

**Comment by schristley** [comment]
Looks good Brian, I will make some edits after I give it some thought. We probably do want to list two for VDJServer as we have one for iReceptor and another for our public data portal.

**Comment by bcorrie** [comment]
I am going to close this issue, as the list has been created... People can feel free to add/edit of course.
