### ISSUE TITLE
Review CRWG Recommendations document

### ISSUE THREAD

**Issue by bcorrie** [airr-community/common-repo-wg#27]
It is probably time to review these as we approach the May meeting.

I have created a branch that we can use to make changes... 

https://github.com/airr-community/common-repo-wg/blob/issue-27/recommendations.md

**Comment by bcorrie** [comment]
It appears to me that Recommendation 8 and 9 should be reviewed...

**Comment by bcorrie** [comment]
There also appears to be a gap in what I would consider as our main goal of this year - defining an API that makes it possible to perform consistent queries across AIRR compliant repositories.

**Comment by lgcowell** [comment]
﻿Right, of course the whole recommendations documented will need to be updated to reflect this work.

**Comment by bussec** [comment]
My two cents on the current version:
* Rec. 10: PII and PHI are - best to my knowledge - US legal terms. We should use more generic wording that also captures European GDPR.
* Rec. 13: We should make sure that IEDB can capture all metadata required by MiAIRR. Otherwise this recommendation should be rephrased and recommend deposition at IEDB as a secondary submission (cross-referencing to and cross-referenced by the primary repository).
* Rec. 14: Do we still have any contact with ImmPort? What is the level of implementation there?

**Comment by lgcowell** [comment]
Christian and everyone, see my inline comments below in blue. Thanks!

> * Rec. 10: PII and PHI are - best to my knowledge - US legal terms. We should use more generic wording that also captures European GDPR.

Do you happen to know what the terms are?

> Rec. 13: We should make sure that IEDB can capture the all metadata required by MiAIRR, otherwise this recommendation should be rephrased and recommend deposition at IEDB as a secondary submission (cross-referencing to and cross-referenced by the primary repository.

Bjoern was heavily involved in the writing of the recommendations, including this particular recommendation, so I think it is safe to assume that they are making IEDB MiAIRR compliant.

> Rec. 14: Do we still have any contact at ImmPort? What is the level of implementation there?

My most recent communications with ImmPort were in September 2018. I can reach out again to confirm, but they were very happy to do this. They do not want to deal with sequencing data directly.

**Comment by bcorrie** [comment]
> It appears to me that Recommendation 8 and 9 should be reviewed...

@laserson would you be able to have a look at Recommendation 8 here: https://github.com/airr-community/common-repo-wg/blob/issue-27/recommendations.md 

I have removed mention of Avro, Thrift, and Protocol Buffers and left in the generic text. Our recollection was that you had suggested these originally.

**Comment by laserson** [comment]
lgtm

**Comment by bussec** [comment]
@lgcowell, I did more reading regarding Rec. 10 and we should probably have someone with a legal background go over this:

>> * Rec. 10: PII and PHI are - best to my knowledge - US legal terms. We should use more generic wording that also captures European GDPR.

> Do you happen to know what the terms are?

* **PII:** The term seems to be a bit fuzzy already in the US, depending on the exact translation (e.g. identifiable vs. identifying). The main issue is that this term does not exist in [GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32016R0679), which typically refers to the much broader term of "personal data" [Art. 4 (1) GDPR].
* **PHI:** This could be described as ''genetic or health data" [Art. 4 (13) & (15) GDPR]]. However, Rec. 10 refers to PHI in regard to metadata only, while from the GDPR perspective the sequencing data itself would already qualify as "genetic data". Note that both genetic and health data are considered "special categories" that underlie enhanced protection [Art. 9 {1} GDPR], typically requiring an informed consent to work with this data [Art. 9 (2) (a) GDPR].

**Comment by bussec** [comment]
@lgcowell, I did more reading regarding Rec. 10 and we should probably have someone with a legal background go over this:

>> * Rec. 10: PII and PHI are - best to my knowledge - US legal terms. We should use more generic wording that also captures European GDPR.

> Do you happen to know what the terms are?

* **PII:** The term seems to be a bit fuzzy already in the US, depending on the exact translation (e.g. identifiable vs. identifying). The main issue is that this term does not exist in [GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32016R0679), which typically refers to the much broader term of "personal data" [Art. 4 (1) GDPR].
* **PHI:** This could be described as ''genetic or health data" [Art. 4 (13) & (15) GDPR]]. However, Rec. 10 refers to PHI in regard to metadata only, while from the GDPR perspective the sequencing data itself would already qualify as "genetic data". Note that both genetic and health data are considered "special categories" that underlie enhanced protection [Art. 9 {1} GDPR], typically requiring an informed consent to work with this data [Art. 9 (2) (a) GDPR].

**Comment by schristley** [comment]
Wasn't this cleaned up and ratified at the last AIRR Community meeting, so we can close?

**Comment by bcorrie** [comment]
Yes, I believe so...

**Comment by bcorrie** [comment]
Closing...
