### ISSUE TITLE
Intellectual Property and AIRR community common repository recommendations

### ISSUE THREAD

**Issue by croweje** [airr-community/common-repo-wg#3]
If funders and journals require deposition in this type of repository but these repositories do not allow for any retention or protection of intellectual property, I believe many of the most important translational studies will be much _less_ accessible, since we'll just drive away investigators and studies that generate medically important receptor discovery. If we want to impact human health, we need commercial parties to develop the discovered molecules, and they need exclusivity through ownership of IP, which in this case will be tightly linked to sequences. The way these guidelines currently read, anyone who wants to discover and pass on for development biomedically important antibodies, CAR-T receptors etc, couldn't really participate in this as I read it.

**Comment by laserson** [comment]
Thanks for the comment, @croweje.  My understanding is that if you deposit data into a repository, our policies do _not_ limit any of your intellectual property rights.  What you do agree to, however, is that you may not use your intellectual property to keep _someone else_ from accessing/using the repository.  In the case of patents, the sequences are published anyway, and in the case of trade secrets, the sequences probably wouldn't be deposited anyway.

(Note: I am not a lawyer, but this language was crafted by one)

**Comment by lgcowell** [comment]
Thanks Uri.  Your understanding is consistent with my understanding.

**Comment by tbkepler** [comment]
This is the key stumbling block, and we need to make sure it is stated correctly. Let's take a concrete scenario. I have an antibody that I have patented, and I would like to deposit it and its metadata into the repository. The language of the recommendation states: "Depositors of data and repositories should have no right to interfere with access to and use of the data by others, including through the assertion of any intellectual property rights." This explicitly goes beyond "access" to include "use". 

I'm puzzled at the claim that these policies "do no limit any of [the depositor's] intellectual property rights" while denying his or her ability to "interfere with ...use...through the assertion of _any_ intellectual property rights". Emphasis added. IP is specifically meant to interfere with certain kinds of use.

If what we are intending is to prevent interference with access, then we should not mention use. If we want to prevent interference with use not otherwise protected by existing IP, we should say that.

**Comment by lgcowell** [comment]
Hi Tania – I just wanted to make sure you are seeing the comments coming in over the issue tracker regarding the IP language.  If you are not currently subscribed and need help with that, just let me know.

**Comment by croweje** [comment]
Everyone seems to be assuming that antibody and TCR sequences are patentable, but they are not necessarily so. If there is not patent protection, then the only way to keep them useful for commercial development is to keep them proprietary. Let me give a variation of Tom's scenario. I have a medically important antibody. I know the sequence. I don't believe I can obtain patent protection after Myriad on a naturally occurring antibody sequence. I license the antibody sequence to a pharma company and they commit to investing millions to develop it, as a public health measure. If I am compelled to deposit and reveal that sequence, typically I am going to violate the licensure agreements, and kill the development. And the benefits of translating basic science discoveries into products that help people is undermined. 

One longer term strategy that is being used in industry is to engineer the sequences, obtain patents on those which is more straightforward, and then deposit in a repository. But engineering just to protect IP because journals and NIH want to force disclosure of "all" genetic data, it becomes a game that is not necessarily the best biology or medicine.

**Comment by croweje** [comment]
I guess also, there are two separable issues that we are mixing here. One is the funding or journal policy requiring public deposition of all proprietary information associated with grants or contracts into a public repository without some accommodation to ensure the ability to develop products, that is the most problematic issue from my standpoint. The second is the data access/use policy of the repository, which is easy to fix. The database can't really regulate the first issue. But in this community, the issues are linked. So we should think through the implications in a linked manner.

**Comment by laserson** [comment]
@croweje, I'm not sure I understand your scenario perfectly.  Do you mean a situation in which I, as a researcher, have a medically useful antibody sequence that is currently secret but has an associated publication?  The publication perhaps describes the development of the antibody, and also its useful properties, but specifically leaves out the actual antibody sequence?  The situation you are worried about is that the journal would compel me to put the sequence in the repository even though I want to keep it secret?

**Comment by cmurawsky** [comment]
There is already little incentive for companies to publish or publicly share their AIRR data and this is usually driven by individual motivated scientists, rather than company policy. I am afraid that imposing policies that can (and will) be interpreted as compromising the Intellectual Property position of the depositor will result in making it even more difficult to have industry engage. As tbkepler states, the specifics of the language used here is key. Perhaps we need to consult with industry (specifically industry lawyers) to get a feel for what their positions would be with the current recommendations? Either that, or build in a mechanism for some kind of flexibility to accommodate the inevitable legal negotiations that will be required to allow industry researchers to publish their data.

**Comment by croweje** [comment]
Exactly. The journal, or the funder (NIH etc) may seek to require deposition of proprietary information that cannot be protected by patent, but this information is essential to protect in order to maintain commercial viability.
Often sequence features (variable genes, # mutations, CDR3 length) are published without compromising the ownership of the full length expressible sequence. Such sequences normally could be distributed under a CDA for academic purposes, but it is unwise to just categorically require public deposition of all sequences without any regard to the impact on the likelihood that sequence could be used under licensure to develop new candidate therapies.

**Comment by lgcowell** [comment]
The recommendations document has been updated in the branch lgc-2016.11.16 to reflect recent discussions surrounding the IP language.  Please review and comment on this revised version.  If everyone is happy with these revisions, we will proceed to a community vote.  Try to comment before Thanksgiving ... Thanks!

**Comment by bussec** [comment]
I am 100% against the kind of exception as it now has been introduced in recommendation #2. The large nucleic acid databases (INSDC, i.e. Genbank, EBI and DDBJ) have had a simple and strict open access policy for years and I think it served them and the community well. The proposed exception in contrast is unclear (what is an "exceptional circumstance") and inhibits the free distribution of information. Most important: Who decides whether an exception should be made? I don't think that we want to get into this question and all it ramification at this point.

There has been some discussion that strict requirements for full disclosure might reduce the number of published Ig/TCR as it could be detrimental to IP protection. While I agree that this might be true in individual cases, I think that more often people/entities concerned about IP protection would rather not publish at all, as it might be hard to determine which information is "safe" to release. Furthermore, in my opinion it would be helpful for this discussion, if the "pro-IP" proponents could come up with concrete examples of public biological databases with mixed levels of disclosure.

**Comment by croweje** [comment]
Right, the databases themselves (for ex GenBank as you reference) are open access, and AIRR is also suggesting immune repertoire databases be open access. What we are discussing is the idea of sponsor and journal requirements to deposit _by default_ all nucleic acid sequences. I could give you plenty of examples in which commercially valuable antibodies and TCRs are described in papers for biological function without the sequence, that is what we are talking about. That allows investigators to describe in detail medically important advances, which is valuable to the community, without disclosing proprietary information that cannot be protected by patents after Myriad, but for which exclusive ownership is necessary to obtain commercial commitment for development. 

The NIH already recognizes this principle in the preaward process in which information can be marked proprietary (even though preaward application documents are considered confidential already) and that proprietary information is not even disclosed under Freedom of Information Act requests.

We have to achieve a balance between everyone's desire for full information sharing and the competing desire for development of medically beneficial interventions.

**Comment by lgcowell** [comment]
This issue was addressed with revisions to Recommendat 4 at the AIRR community meeting in December 2017.

**Comment by tbkepler** [comment]
Hi, Lindsay.

I’m sorry I wasn’t able to get away to catch up with you.
How was the meeting?

Best wishes,
Tom

Thomas B. Kepler, Professor
Department of Microbiology (and Department of Mathematics & Statistics)
Boston University School of Medicine
72 E. Concord St., L504D
Boston MA 02118
Voice: +1 617 638 4124
