### ISSUE TITLE
Recommendation 12: IEDB scope?

### ISSUE THREAD

**Issue by scottdbrown** [airr-community/common-repo-wg#5]
Will IEDB accept submitted data for all epitopes/antigen receptors? I have notes from them that their scope is "infectious diseases, allergy, autoimmunity, and transplant", and "HIV, cancer, etc only curated as structural data or when presented with above subjects as per NIH/NIAID".

**Comment by bpeters42** [comment]
Short answer: Yes, the IEDB will take all data on epitope specific receptor sequences. 
Long answer: Whenever general rules of epitope:receptor interactions can be learned from data, even if that data was generated for epitopes outside our scope,  the IEDB is accepting such data. Examples that we have a lot of are MHC binding data or Antibody:Antigen crystal structures. Sequence data for epitope specific antibodies or TCRs where both epitope and receptor are defined fall into this category as well.
